#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Authored for: Google Health API setup on this Mac, for CLI food logging.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Keep every captured value next to the wizard itself, not in the parent repo.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env"
GHEALTH_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/google-health-cli"

banner "Google Health API setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites: Go and jq"
say "ghealth is a Go program, so we need a Go toolchain. jq is already here."
if command -v go >/dev/null 2>&1; then
  say "Go is already installed: $(go version)"
else
  warn "No Go toolchain found."
  if confirm "Install Go now with Homebrew?"; then
    brew install go
    hash -r                     # drop bash's cached 'go not found'
  else
    SKIPPED+=("install Go (brew install go), then re-run this wizard")
    warn "Skipping. Stage 2 will fail without it."
  fi
fi
command -v jq >/dev/null 2>&1 || SKIPPED+=("install jq (brew install jq)")
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Build the ghealth CLI"
say "Cloning Google's official CLI and building it into this folder."
if [[ -x "$GHEALTH_SRC/ghealth" ]]; then
  say "Already built at $GHEALTH_SRC/ghealth"
else
  if [[ -d "$GHEALTH_SRC/.git" ]]; then
    git -C "$GHEALTH_SRC" pull --ff-only
  else
    git clone https://github.com/Google-Health-API/google-health-cli "$GHEALTH_SRC"
  fi
  ( cd "$GHEALTH_SRC" && go build -o ghealth . )
  say "Built: $GHEALTH_SRC/ghealth"
fi
note "Add it to your PATH later with:"
note "  ln -sf $GHEALTH_SRC/ghealth /usr/local/bin/ghealth"
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create a Google Cloud project"
say "Everything hangs off one throwaway GCP project. It is free."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something like 'health-cli'. Leave the organisation as-is."
step "Click CREATE, wait for it, then copy the Project ID (not the name)."
note "The ID is lowercase with digits, e.g. health-cli-481207."
ask GCP_PROJECT_ID "Paste the Project ID:"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Enable the Google Health API"
say "The project needs the Health API switched on before any call works."
open_url "https://console.cloud.google.com/apis/api/health.googleapis.com/overview?project=${GCP_PROJECT_ID}"
step "Click ENABLE. If it already says 'API enabled', you are done here."
pause "Press Enter once it is enabled"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Auth Platform: branding and audience"
say "The old 'OAuth consent screen' now lives under Google Auth Platform."
open_url "https://console.cloud.google.com/auth/branding?project=${GCP_PROJECT_ID}"
step "If prompted, click GET STARTED."
step "App name: anything ('health-cli'). User support email: your own."
step "Audience: choose EXTERNAL. Contact email: your own. Then create."
say ""
open_url "https://console.cloud.google.com/auth/audience?project=${GCP_PROJECT_ID}"
step "Under 'Test users', click ADD USERS and add your own Google address."
warn "Do this even though it is your own project. Without it, login is refused."
pause "Press Enter when your email is listed as a test user"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Auth Platform: publishing status"
say "This stage decides whether your login survives longer than a week."
note "In 'Testing', refresh tokens expire after 7 days. Publishing removes that."
say ""
warn "Yes, every Google Health scope is RESTRICTED."
say "Restricted scopes normally require verification plus a CASA third-party"
say "security assessment. You do not need either one here, because Google"
say "exempts personal use: 'apps with only yourself or a handful of known"
say "users' can skip verification entirely."
say ""
say "So publish it unverified. You pay exactly two prices:"
step "A 'Google hasn't verified this app' screen at login. Click through once."
step "A hard cap of 100 total users. You are one of them."
note "Neither the cap nor the warning affects a single-user setup."
say ""
open_url "https://console.cloud.google.com/auth/audience?project=${GCP_PROJECT_ID}"
step "On the Audience page, click PUBLISH APP and confirm."
step "Do NOT click 'Prepare for verification' or submit anything."
say ""
if confirm "Does the page now show 'In production'?"; then
  write_env GH_PUBLISHING_STATUS "in_production"
  say "Good. Your refresh token will persist until revoked or ~6 months idle."
else
  write_env GH_PUBLISHING_STATUS "testing"
  warn "Still in Testing, so tokens die every 7 days."
  note "Re-run 'ghealth auth login' when calls start returning 401."
  SKIPPED+=("weekly re-auth needed while the consent screen stays in Testing")
fi
pause "Press Enter to continue"

stage "Auth Platform: food and weight scopes"
say "Declare nutrition and health metrics scopes, each with read AND write."
open_url "https://console.cloud.google.com/auth/scopes?project=${GCP_PROJECT_ID}"
step "Click ADD OR REMOVE SCOPES."
step "In the filter box, search: googlehealth"
step "Tick all FOUR of these, then UPDATE and SAVE:"
note "    .../auth/googlehealth.nutrition.readonly"
note "    .../auth/googlehealth.nutrition.writeonly"
note "    .../auth/googlehealth.health_metrics_and_measurements.readonly"
note "    .../auth/googlehealth.health_metrics_and_measurements.writeonly"
warn "writeonly is the one that lets you log food. Do not skip it."
say ""
say "A 'Verification required' dialog will pop up when you add these."
step "Dismiss it. Do not submit anything."
note "It is the entry point to start verification, not a gate. Verification is"
note "not required in Testing, nor for personal use at all."
step "Then reload the page and confirm all four scopes are still listed."
pause "Press Enter once all four scopes are saved and still showing"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Create a Desktop OAuth client"
say "ghealth logs in over a local loopback port, so it needs a DESKTOP client."
open_url "https://console.cloud.google.com/auth/clients?project=${GCP_PROJECT_ID}"
step "Click CREATE CLIENT."
step "Application type: Desktop app   <-- not Web application."
step "Name it 'ghealth', click CREATE, then DOWNLOAD JSON."
warn "Web application is the wrong type here and login will fail with it."
ask CLIENT_SECRET_PATH "Path to the downloaded JSON (drag the file in here):"
CLIENT_SECRET_PATH="${CLIENT_SECRET_PATH//\'/}"          # strip quotes from drag-and-drop
CLIENT_SECRET_PATH="${CLIENT_SECRET_PATH/#\~/$HOME}"
if [[ -f "$CLIENT_SECRET_PATH" ]]; then
  write_env CLIENT_SECRET_PATH "$CLIENT_SECRET_PATH"
else
  warn "No file at that path; ghealth setup will ask you for it again."
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Authenticate, then verify a read and a write"
say "ghealth has its own 6-step setup. We hand it everything it needs."
say ""
note "Running:"
note "  ghealth setup --project-id $GCP_PROJECT_ID \\"
note "      --client-secret <your json> --skip-enable-api \\"
note "      --scopes nutrition.readonly,nutrition.writeonly,health_metrics_and_measurements.readonly,health_metrics_and_measurements.writeonly"
say ""
warn "A browser window will open. Pick your Google account and accept."
warn "On the 'Google hasn't verified this app' screen: Advanced -> Go to ..."
pause "Press Enter to launch it"
# macOS ships bash 3.2, where "${arr[@]}" on an empty array aborts under
# set -u, so branch instead of splicing an optional flag.
if [[ -n "${CLIENT_SECRET_PATH:-}" ]]; then
  "$GHEALTH_SRC/ghealth" setup \
    --project-id "$GCP_PROJECT_ID" \
    --client-secret "$CLIENT_SECRET_PATH" \
    --skip-enable-api \
    --scopes "nutrition.readonly,nutrition.writeonly,health_metrics_and_measurements.readonly,health_metrics_and_measurements.writeonly" || \
    warn "Setup exited non-zero. Re-run it by hand to see the error."
else
  "$GHEALTH_SRC/ghealth" setup \
    --project-id "$GCP_PROJECT_ID" \
    --skip-enable-api \
    --scopes "nutrition.readonly,nutrition.writeonly,health_metrics_and_measurements.readonly,health_metrics_and_measurements.writeonly" || \
    warn "Setup exited non-zero. Re-run it by hand to see the error."
fi

say ""
say "Checking which scopes the token actually carries:"
"$GHEALTH_SRC/ghealth" auth export 2>/dev/null | jq -r '.scopes[]?' || \
  warn "Could not read scopes; is login complete?"
say ""
warn "Confirm nutrition and health_metrics_and_measurements read/write scopes appear."
warn "If either write scope is missing, the corresponding write"
warn "path will 403 and you need to re-run: ghealth auth login --scopes ..."
say ""
say "Reading your existing food logs (may legitimately be empty):"
"$GHEALTH_SRC/ghealth" data nutrition-log list --format table 2>&1 | head -20 || true
pause "Press Enter for the summary"

finish
say "Next: log a meal in the Google Health app on your phone, then run"
note "  ghealth data nutrition-log list --raw --limit 1"
note "to capture the exact JSON shape before wiring up the flog script."
printf '\n'
